swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    
    
    
    MAILER_URL=gmail://localhost:25?encryption=ssl&auth_mode=login&username= David Larose&password= alanmarivat5

